### PR TITLE
Add description that is easy to find

### PR DESCRIPTION
**Pull request by ShalokShalom**
The current description gives no result when looking for "Adobe" or "Flash" or even "Firefox"

### CODE REVIEW

**Comment by demmm** [comment]
See what the devs call this:
https://github.com/i-rinat/freshplayerplugin
And it certainly is not Adobe Flash, that is covered with pepper-flash.

**Comment by ShalokShalom** [comment]
Yeah, it could also be called Pepper-flash for Firefox. 

Does not change anything that pp2pskksljfisadv is not findable by any human beings. No reason to make it more difficult for the user base on purpose. 

Thanks

**Comment by demmm** [comment]
There are several ways in place already to inform all of how to use pepper-flash with Firefox.  If you would care to read instructions on installing Firefox, you get the info, if you would care to read the info on installing or updating pepper-flash, you get the info.
And no, this is NOT pepper-flash for Firefox, it is a needed layer to make pepper-flash work on Firefox, so please stop from using pull request to spam.

**Comment by ShalokShalom** [comment]
The description is not declarative. I dont know what is so difficult to understand. If you would care about your users ability to find stuff, you would not need to deal with the feedback. Currently, this description is point less and you are just too stubborn to accept, as so often.

**Pull request closed without merging**
