### PR TITLE
Correct skype icon

### PR DESCRIPTION
**Pull request by bvbfan**

### CODE REVIEW

**Comment by demmm** [comment]
Why is the actions icon needed and not the usual apps icon?

**Comment by bvbfan** [comment]
Or you should provide icon as well, i don't have icon called simple skype on my installation.

**Comment by demmm** [comment]
It is part of every KaOS install, it being available in midna & midna-dark, so it is already provided
apps/midna-themes 3.0.3-1               /usr/share/icons/midna/apps/48/skype.svg
apps/midna-themes 3.0.3-1               /usr/share/icons/midnadark/apps/48/skype.svg

**Comment by bvbfan** [comment]
Ok, if it's not a problem, when you uninstall Midna theme to does not have an icon is ok. I mean icon should be here or kde-common to depend on Midna (which will be disaster) or we can leave as is.

**Comment by demmm** [comment]
I'll add the icon to kde-common, so it won't be an actions icon for an app/menu entry.  Thus won't be using this pull request.

**Comment by demmm** [comment]
And as a many times repeated note (last time), do not flag packages as outdated when you find an issue, those will be ignored and immediately removed.  Use the proper bug reports channels.
https://kaosx.us/bugs

**Pull request closed without merging**
